version: "1"
branch: main
fallbackBranches: []
sync:
  enabled: true
  packPaths:
    - packs/*.zopack.md
  onEvents: push, workflow_dispatch
events:
  push: sync
  workflow_dispatch: sync
agent:
  priorStateKey: zo-gh:EthanThatOneKid/setup-zo-poc
space:
  url: https://etok.zo.space
mirror:
  workspacePath: /home/workspace/code/github.com/EthanThatOneKid/setup-zo-poc-mirror
feedback:
  commitComment:
    enabled: false
